# Generated by Django 6.0.7 on 2026-08-23 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_contact', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('SCHEDULED', 'Scheduled')], default='SENT', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('DUE_REMINDER', 'Dues Reminder'), ('WELFARE', 'Welfare'), ('GENERAL', 'General'), ('ANNOUNCEMENT', 'Announcement')], default='GENERAL', max_length=20)),
                ('message_type', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], default='SMS', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(help_text='Use {{name}} {{amount}} {{date}} placeholders')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='outgoingmessage',
            options={'ordering': ['-sent_at']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('EVENT', 'Event'), ('WELFARE', 'Welfare'), ('FINANCE', 'Finance'), ('URGENT', 'Urgent')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='announcement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outgoingmessage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outgoingmessage',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outgoingmessage',
            name='recipient_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outgoingmessage',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outgoingmessage',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('SCHEDULED', 'Scheduled')], default='SENT', max_length=20),
        ),
        migrations.AddField(
            model_name='outgoingmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_active', 'category'], name='communicati_is_acti_8fcd1f_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['created_at'], name='communicati_created_cd9d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='outgoingmessage',
            index=models.Index(fields=['message_type', 'status'], name='communicati_message_db743c_idx'),
        ),
        migrations.AddIndex(
            model_name='outgoingmessage',
            index=models.Index(fields=['sent_at'], name='communicati_sent_at_ec4e7c_idx'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='outgoing_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='communications.outgoingmessage'),
        ),
    ]
