# Generated by Django 6.0.7 on 2026-08-23 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classgroup',
            options={'ordering': ['name'], 'verbose_name': 'Bible Study Class', 'verbose_name_plural': 'Bible Study Classes'},
        ),
        migrations.AddField(
            model_name='classgroup',
            name='assistant_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='capacity',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='category',
            field=models.CharField(choices=[('BIBLE_STUDY', 'Bible Study'), ('SUNDAY_SCHOOL', 'Sunday School'), ('YOUTH', 'Youth Class'), ('ADULT', 'Adult Class'), ('NEW_CONVERT', 'New Convert'), ('OTHER', 'Other')], default='BIBLE_STUDY', max_length=20),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='location',
            field=models.CharField(blank=True, default='Main Chapel', max_length=150),
        ),
        migrations.CreateModel(
            name='ClassMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='classes.classgroup')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('class_group', 'date')},
            },
        ),
    ]
