# Generated by Django 6.0.7 on 2026-08-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('UTILITIES', 'Utility Bills (Water/Electricity)'), ('WELFARE', 'Member Welfare Support'), ('MAINTENANCE', 'Sanctuary Maintenance'), ('REPAIRS', 'Repairs & Equipment'), ('TRANSPORT', 'Transport & Fuel'), ('EVANGELISM', 'Evangelism & Mission'), ('ADMIN', 'Administrative Supplies'), ('STATUTORY', 'Statutory / Connexional Payments'), ('OTHER', 'Other Expenditure')], default='OTHER', max_length=100),
        ),
        migrations.AlterField(
            model_name='expenseledger',
            name='category',
            field=models.CharField(choices=[('UTILITIES', 'Utility Bills (Water/Electricity)'), ('WELFARE', 'Member Welfare Support'), ('MAINTENANCE', 'Sanctuary Maintenance'), ('REPAIRS', 'Repairs & Equipment'), ('TRANSPORT', 'Transport & Fuel'), ('EVANGELISM', 'Evangelism & Mission'), ('ADMIN', 'Administrative Supplies'), ('STATUTORY', 'Statutory / Connexional Payments'), ('OTHER', 'Other Expenditure')], default='OTHER', max_length=30),
        ),
    ]
