# Generated by Django 6.0.7 on 2026-08-18 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_normalise_expense_categories'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeledger',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MOMO', 'Mobile Money'), ('BANK', 'Bank Transfer'), ('CHEQUE', 'Cheque')], default='CASH', max_length=10),
        ),
        migrations.AddField(
            model_name='incomeledger',
            name='reference',
            field=models.CharField(blank=True, help_text='MoMo transaction ID or cheque number.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incomeledger',
            name='service',
            field=models.ForeignKey(blank=True, help_text='The service or event this income was collected at.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_entries', to='services.churchservice'),
        ),
    ]
