# Generated by Django 6.0.7 on 2026-08-23 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_membertransfer'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, help_text='For guests not in member directory', max_length=150)),
                ('is_present', models.BooleanField(default=True)),
                ('is_guest', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProgramItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=5)),
                ('responsible_person', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='churchservice',
            options={'ordering': ['service_date', 'start_time']},
        ),
        migrations.AddField(
            model_name='churchservice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='churchservice',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='churchservice',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='churchservice',
            name='location',
            field=models.CharField(default='Main Auditorium', max_length=200),
        ),
        migrations.AddField(
            model_name='churchservice',
            name='service_type',
            field=models.CharField(choices=[('SUNDAY', 'Sunday Service'), ('WEEKDAY', 'Weekday Service'), ('BIBLE_STUDY', 'Bible Study'), ('PRAYER', 'Prayer Meeting'), ('REVIVAL', 'Revival / Crusade'), ('FUNERAL', 'Funeral Service'), ('WEDDING', 'Wedding'), ('SPECIAL', 'Special Programme'), ('OTHER', 'Other')], default='SUNDAY', max_length=20),
        ),
        migrations.AddField(
            model_name='churchservice',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('POSTPONED', 'Postponed')], default='SCHEDULED', max_length=20),
        ),
        migrations.AddField(
            model_name='churchservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='churchservice',
            index=models.Index(fields=['service_date', 'status'], name='services_ch_service_68ddde_idx'),
        ),
        migrations.AddIndex(
            model_name='churchservice',
            index=models.Index(fields=['service_type'], name='services_ch_service_090a47_idx'),
        ),
        migrations.AddField(
            model_name='serviceattendance',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_attendances', to='members.member'),
        ),
        migrations.AddField(
            model_name='serviceattendance',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceattendance',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='services.churchservice'),
        ),
        migrations.AddField(
            model_name='serviceprogramitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_items', to='services.churchservice'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceattendance',
            unique_together={('service', 'member')},
        ),
    ]
