# Generated by Django 6.0.7 on 2026-08-23 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_sensitive', models.BooleanField(default=False, help_text='Marks sensitive modules like Welfare')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_system_protected', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('SUPERINTENDENT_MINISTER', 'Superintendent Minister'), ('SOCIETY_STEWARD', 'Society Steward'), ('LEADERS_MEETING_SECRETARY', 'Leaders’ Meeting Secretary'), ('AUDITOR', 'Auditor'), ('TREASURER', 'Treasurer'), ('CATECHIST', 'Catechist'), ('CIRCUIT_MINISTER', 'Circuit Minister'), ('BIBLE_STUDY_LEADER', 'Bible Study Leaders'), ('CLASS_LEADER', 'Class Leader'), ('ORGANISATION_LEADER', 'Organisation Leaders'), ('FINANCIAL_SECRETARY', 'Financial Secretary'), ('SOCIETY_MINISTER', 'Society Minister'), ('WELFARE_OFFICER', 'Welfare Officer'), ('MEMBER', 'Society Member')], default='MEMBER', max_length=40),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.module')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.role')),
            ],
            options={
                'ordering': ['role__name', 'module__order'],
                'unique_together': {('role', 'module')},
            },
        ),
    ]
