# Generated by Django 6.0.7 on 2026-08-06 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('MEMBERSHIP', 'Membership Report'), ('ATTENDANCE', 'Attendance Report'), ('FINANCIAL', 'Financial Report'), ('WELFARE', 'Welfare Report'), ('ANNUAL', 'Annual / Quarterly Report')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
