# Generated by Django 6.0.7 on 2026-08-23 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('MEMBERSHIP', 'Membership Report'), ('ATTENDANCE', 'Attendance Report'), ('FINANCIAL', 'Financial Report'), ('WELFARE', 'Welfare Report'), ('ANNUAL', 'Annual / Quarterly Report'), ('CUSTOM', 'Custom Report')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], default='MONTHLY', max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_run'],
            },
        ),
        migrations.AlterModelOptions(
            name='generatedreportlog',
            options={'ordering': ['-is_pinned', '-generated_at']},
        ),
        migrations.AddField(
            model_name='generatedreportlog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedreportlog',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='generatedreportlog',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedreportlog',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Filters used to generate report'),
        ),
        migrations.AddField(
            model_name='generatedreportlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived')], default='GENERATED', max_length=20),
        ),
        migrations.AddField(
            model_name='generatedreportlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='generatedreportlog',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generatedreportlog',
            name='report_type',
            field=models.CharField(choices=[('MEMBERSHIP', 'Membership Report'), ('ATTENDANCE', 'Attendance Report'), ('FINANCIAL', 'Financial Report'), ('WELFARE', 'Welfare Report'), ('ANNUAL', 'Annual / Quarterly Report'), ('CUSTOM', 'Custom Report')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='generatedreportlog',
            index=models.Index(fields=['report_type', 'status'], name='reports_gen_report__c8f04d_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreportlog',
            index=models.Index(fields=['generated_at'], name='reports_gen_generat_e08195_idx'),
        ),
        migrations.AddField(
            model_name='reportfavorite',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='reports.generatedreportlog'),
        ),
        migrations.AddField(
            model_name='reportfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reportfavorite',
            unique_together={('user', 'report')},
        ),
    ]
