# Generated by Django 6.0.7 on 2026-08-23 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_membertransfer'),
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('venue', models.CharField(blank=True, max_length=150)),
                ('minutes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRESIDENT', 'President'), ('VICE_PRESIDENT', 'Vice President'), ('SECRETARY', 'Secretary'), ('TREASURER', 'Treasurer'), ('MEMBER', 'Member')], default='MEMBER', max_length=20)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-joined_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='organisationdues',
            options={'ordering': ['-date_paid', '-created_at']},
        ),
        migrations.AddField(
            model_name='organisation',
            name='category',
            field=models.CharField(choices=[('FELLOWSHIP', 'Fellowship'), ('CHOIR', 'Choir'), ('YOUTH', 'Youth Ministry'), ('MEN', "Men's Fellowship"), ('WOMEN', "Women's Fellowship"), ('CHILDREN', 'Children Ministry'), ('EVANGELISM', 'Evangelism'), ('OTHER', 'Other')], default='FELLOWSHIP', max_length=20),
        ),
        migrations.AddField(
            model_name='organisation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='location',
            field=models.CharField(blank=True, default='Main Chapel', max_length=150),
        ),
        migrations.AddField(
            model_name='organisation',
            name='secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_organisations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisation',
            name='treasurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasurer_organisations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='organisationdues',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='organisationdues',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_dues', to='members.member'),
        ),
        migrations.AddField(
            model_name='organisationdues',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Bank Transfer')], default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='organisationdues',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organisationdues',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_org_dues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisationdues',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='organisationdues',
            index=models.Index(fields=['date_paid'], name='organisatio_date_pa_326e1d_idx'),
        ),
        migrations.AddField(
            model_name='organisationmeeting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisationmeeting',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='organisationmembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_memberships', to='members.member'),
        ),
        migrations.AddField(
            model_name='organisationmembership',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organisations.organisation'),
        ),
        migrations.AlterUniqueTogether(
            name='organisationmeeting',
            unique_together={('organisation', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='organisationmembership',
            unique_together={('organisation', 'member')},
        ),
    ]
