# Generated by Django 6.0.7 on 2026-08-06 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WelfareCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('MEDICAL', 'Medical Emergency'), ('BEREAVEMENT', 'Bereavement / Funeral Support'), ('HARDSHIP', 'Financial Hardship'), ('EDUCATION', 'Education / Scholarship'), ('OTHER', 'Other Support')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welfare_cases', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='VisitationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('visitors', models.CharField(help_text='Comma separated list of visiting committee members', max_length=255)),
                ('findings', models.TextField()),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('welfare_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitations', to='welfare_cases.welfarecase')),
            ],
        ),
        migrations.CreateModel(
            name='WelfareDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disbursement_date', models.DateField()),
                ('payment_method', models.CharField(default='Mobile Money', max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('welfare_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement', to='welfare_cases.welfarecase')),
            ],
        ),
    ]
