# Generated by Django 6.0.7 on 2026-08-23 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_membertransfer'),
        ('welfare_cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WelfareCaseActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Case Created'), ('STATUS_CHANGED', 'Status Changed'), ('ASSIGNED', 'Officer Assigned'), ('VISIT_LOGGED', 'Visitation Logged'), ('DISBURSED', 'Disbursement Recorded'), ('NOTE_ADDED', 'Note Added'), ('CLOSED', 'Case Closed')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Welfare case activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='visitationlog',
            options={'ordering': ['-visit_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='welfarecase',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='welfaredisbursement',
            options={'ordering': ['-disbursement_date']},
        ),
        migrations.AddField(
            model_name='visitationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='visitationlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitation_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitationlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='welfarecase',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='welfarecase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_welfare_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='welfarecase',
            name='is_confidential',
            field=models.BooleanField(default=True, help_text='Marks case as confidential'),
        ),
        migrations.AddField(
            model_name='welfarecase',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='welfarecase',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Internal review notes'),
        ),
        migrations.AddField(
            model_name='welfaredisbursement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='welfaredisbursement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='welfaredisbursement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='welfaredisbursement',
            name='payment_method',
            field=models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque')], default='MOBILE_MONEY', max_length=50),
        ),
        migrations.AddIndex(
            model_name='welfarecase',
            index=models.Index(fields=['status'], name='welfare_cas_status_179de8_idx'),
        ),
        migrations.AddIndex(
            model_name='welfarecase',
            index=models.Index(fields=['case_type'], name='welfare_cas_case_ty_58c651_idx'),
        ),
        migrations.AddIndex(
            model_name='welfarecase',
            index=models.Index(fields=['priority'], name='welfare_cas_priorit_490d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='welfarecase',
            index=models.Index(fields=['created_at'], name='welfare_cas_created_139d2c_idx'),
        ),
        migrations.AddField(
            model_name='welfarecaseactivity',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welfare_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='welfarecaseactivity',
            name='welfare_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='welfare_cases.welfarecase'),
        ),
    ]
