# Generated by Django 6.0.7 on 2026-08-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare_cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='welfarecase',
            name='closure_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='welfarecase',
            name='closure_outcome',
            field=models.CharField(
                blank=True,
                choices=[
                    ('RESOLVED', 'Resolved / Improved'),
                    ('DECEASED', 'Deceased'),
                    ('TRANSFERRED', 'Transferred to External Org'),
                    ('WITHDRAWN', 'Member Withdrawn'),
                    ('OTHER', 'Other'),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='welfarecase',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
