# Generated by Django 6.0.7 on 2026-08-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date_of_baptism',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='hometown',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('DIVORCED', 'Divorced')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('FULL', 'Full Member'), ('TRIAL', 'Member on Trial'), ('ADHERENT', 'Adherent')], default='FULL', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='occupation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='organisations',
            field=models.ManyToManyField(blank=True, related_name='members', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='member',
            name='passport_photo',
            field=models.FileField(blank=True, null=True, upload_to='member_photos/'),
        ),
    ]
