# Generated by Django 6.0.7 on 2026-08-19 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('members', '0002_member_date_of_baptism_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active Full Member'), ('PENDING', 'Pending Approval'), ('REGULARIZED', 'Regularized'), ('TRANSFERRED', 'Transferred'), ('INACTIVE', 'Inactive'), ('DECLINED', 'Regularisation Declined')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='MemberRegularisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved for Full Membership'), ('DEFERRED', 'Deferred (Requires Action)'), ('DECLINED', 'Declined')], max_length=20)),
                ('meeting_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('approval_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regularisation_decisions', to='classes.classgroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularisations', to='members.member')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_regularisations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-approval_date', '-created_at'],
            },
        ),
    ]
