# Generated by Django 6.0.7 on 2026-08-19 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_status_memberregularisation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('ACTIVE', 'Active Full Member'), ('PENDING', 'Pending Approval'), ('REGULARIZED', 'Regularized'), ('TRANSFERRED', 'Transferred'), ('INACTIVE', 'Inactive'), ('DECLINED', 'Regularisation Declined')], max_length=20)),
                ('new_status', models.CharField(choices=[('ACTIVE', 'Active Full Member'), ('PENDING', 'Pending Approval'), ('REGULARIZED', 'Regularized'), ('TRANSFERRED', 'Transferred'), ('INACTIVE', 'Inactive'), ('DECLINED', 'Regularisation Declined')], max_length=20)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField()),
                ('authorised_by', models.CharField(choices=[('MINISTER', 'Rev. Superintendent Minister'), ('STEWARD', 'Society Steward'), ('LEADERS_MEETING', 'Leaders Meeting')], max_length=30)),
                ('note_reference', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='members.member')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
