# Generated by Django 5.2.17 on 2026-08-19 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('members', '0004_membershipstatuschange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing')], max_length=3)),
                ('member_name', models.CharField(max_length=200)),
                ('destination_society', models.CharField(blank=True, default='', max_length=150)),
                ('previous_society', models.CharField(blank=True, default='', max_length=150)),
                ('circuit', models.CharField(blank=True, default='', max_length=150)),
                ('letter_reference', models.CharField(blank=True, default='', max_length=100)),
                ('reason', models.CharField(blank=True, choices=[('RELOCATION', 'Relocation'), ('MARRIAGE', 'Marriage'), ('WORK_ASSIGNMENT', 'Work Assignment'), ('OTHER', 'Other')], default='', max_length=30)),
                ('membership_type', models.CharField(blank=True, choices=[('FULL', 'Full Member'), ('TRIAL', 'Member on Trial'), ('ADHERENT', 'Adherent')], default='', max_length=20)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='classes.classgroup')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='members.member')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
    ]
