# Generated by Django 6.0.7 on 2026-08-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemnotification',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('WELFARE', 'Welfare'), ('FINANCE', 'Finance'), ('COMMS', 'Comms'), ('CLASSES', 'Classes'), ('MEMBERS', 'Members')], default='GENERAL', max_length=20),
        ),
    ]
