# Generated by Django 6.0.7 on 2026-08-06 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('members', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='classes.classgroup')),
                ('present_members', models.ManyToManyField(blank=True, related_name='class_attendances', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male_count', models.PositiveIntegerField(default=0)),
                ('female_count', models.PositiveIntegerField(default=0)),
                ('children_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='services.churchservice')),
            ],
        ),
    ]
