# Generated by Django 6.0.7 on 2026-08-23 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_organisationattendancerecord'),
        ('classes', '0001_initial'),
        ('members', '0005_membertransfer'),
        ('organisations', '0001_initial'),
        ('services', '0002_serviceattendance_serviceprogramitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenteeFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('follow_up_status', models.CharField(choices=[('PENDING', 'Pending Follow-up'), ('CONTACTED', 'Contacted'), ('VISITED', 'Visited'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('followed_up_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-absence_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_service_attendance', models.PositiveIntegerField(default=0)),
                ('total_class_attendance', models.PositiveIntegerField(default=0)),
                ('total_org_attendance', models.PositiveIntegerField(default=0)),
                ('total_absentees', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='classattendancerecord',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='organisationattendancerecord',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='serviceattendance',
            options={'ordering': ['-service_date', '-recorded_at']},
        ),
        migrations.AddField(
            model_name='classattendancerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='classattendancerecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_attendance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classattendancerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='organisationattendancerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='organisationattendancerecord',
            name='female_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organisationattendancerecord',
            name='male_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organisationattendancerecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_attendance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisationattendancerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceattendance',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceattendance',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_attendance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceattendance',
            name='service_date',
            field=models.DateField(blank=True, help_text='Date of service, defaults to service date', null=True),
        ),
        migrations.AddField(
            model_name='serviceattendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='classattendancerecord',
            unique_together={('class_group', 'date')},
        ),
        migrations.AddIndex(
            model_name='classattendancerecord',
            index=models.Index(fields=['date'], name='attendance__date_6c843b_idx'),
        ),
        migrations.AddIndex(
            model_name='organisationattendancerecord',
            index=models.Index(fields=['date'], name='attendance__date_dbf479_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceattendance',
            index=models.Index(fields=['service_date'], name='attendance__service_681e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceattendance',
            index=models.Index(fields=['recorded_at'], name='attendance__recorde_136170_idx'),
        ),
        migrations.AddField(
            model_name='absenteefollowup',
            name='followed_up_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absenteefollowup',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absentee_followups', to='members.member'),
        ),
        migrations.AlterUniqueTogether(
            name='absenteefollowup',
            unique_together={('member', 'absence_date')},
        ),
    ]
